### ISSUE TITLE
wrong evaluation for deterministic tree

### ISSUE THREAD

**Issue by rezaarmand** [tomsal/endtoenddecisiontrees#1]
Hi Thomas,

When you want to calculate the performance of the deterministic tree, you just set the "discrete" variable as True in the root node of the tree and not pass it to the child nodes. The related code is on lines 320-326 of the core.py file. You can also check that by calculating the number of unique tree predictions (which should be less than the number of leaf nodes but it is actually way more) for a training data when the discrete option is True. I believe the code can be fixed by changing the following line to * self.right_child(X, discrete) + (1 - gating) * self.left_child(X, discrete). However, that change depreciates the results reported in the paper.

The original coding now is:
  def forward(self, X, discrete=False): 
    if not self._path_end:
      gating = self.gating(X)
      if discrete:
        gating = gating.round()
      return gating       * self.right_child(X)\
           + (1 - gating) * self.left_child(X)

**Comment by tomsal** [comment]
Hi,
first of all, thanks for pointing this out and sorry that I haven't responded to this earlier. I was completely surprised when I know found your issue now. I don't remember receiving a github notification at the time of the posting or it got lost between other emails. So I only found your issue now while randomly checking the repo for the first time since a long time ago. :(

Anyway, this seems indeed like a bug, but I need to take a closer look. Did you by any chance run some tests with your fix?

**Comment by tomsal** [comment]
So, it has been a while, but I've rerun the relevant experiments. Below are the results which show only small differences. Thus, the main conclusions and contributions of the paper do not change. What changes moslty is the sensitivity to the steepness parameter for single trees.

![image](https://user-images.githubusercontent.com/21262762/169292284-711daa52-bc12-4d88-b74b-ed601173b3bf.png)

CNN split features: 98.2% ± 0.1%

![image](https://user-images.githubusercontent.com/21262762/169292532-c0b009fd-3188-4154-a743-b9d4f0c85463.png)
![image](https://user-images.githubusercontent.com/21262762/169292564-eeaa28ff-eedf-45cb-b854-f70451aab955.png)
